version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      tags:
        - orthoviewer/backend:latest
        - orthoviewer/backend:local
    image: orthoviewer/backend:local
    container_name: orthoviewer-backend-local
    volumes:
      - ./data:/app/data
      - ./backend:/app  # Mount source code for development
    environment:
      - PYTHONPATH=/app
      - QT_QPA_PLATFORM=offscreen
      - DISPLAY=
      - ENV=development
    ports:
      - "8003:8002"  # Expose backend directly for development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "conda", "run", "-n", "orthoviewer2", "python", "-c", "import requests; requests.get('http://localhost:8002/api/health/', timeout=5).raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
      tags:
        - orthoviewer/frontend:latest
        - orthoviewer/frontend:local
    image: orthoviewer/frontend:local
    container_name: orthoviewer-frontend-local
    ports:
      - "3000:80"  # Expose frontend directly for development
    restart: unless-stopped
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
      tags:
        - orthoviewer/nginx:latest
        - orthoviewer/nginx:local
    image: orthoviewer/nginx:local
    container_name: orthoviewer-nginx-local
    ports:
      - "8080:80"  # Use port 8080 for local testing
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/health/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:

networks:
  default:
    name: orthoviewer-local 