version: '3.8'

services:
  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile.dev
    container_name: orthoviewer-frontend-dev
    volumes:
      - ./frontend-vite:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_BACKEND_URL=http://localhost:8003
    command: npm run dev -- --host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: orthoviewer-backend-dev
    volumes:
      - ./backend:/app
    ports:
      - "8003:8003"
    environment:
      - PYTHONPATH=/app
      - DEVELOPMENT=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8003 --reload