version: '3.8'

services:
  # Frontend service (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: biosemantic-frontend
    restart: unless-stopped
    ports:
      - "8001:80"
    depends_on:
      - backend
    networks:
      - biosemantic-net

  # Backend service (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: biosemantic-backend
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app
      - ./data:/data
    environment:
      - PYTHONPATH=/app
      - ORTHOFINDER_DATA_DIR=/data/orthofinder
      - CORS_ORIGINS=http://localhost,http://localhost:80,http://localhost:8001,http://frontend:80,http://biosemantic-frontend
    networks:
      - biosemantic-net

  # Nginx as reverse proxy
  nginx:
    image: nginx:alpine
    container_name: biosemantic-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - biosemantic-net
    
networks:
  biosemantic-net:
    driver: bridge 