version: '3.8'

services:
  # Frontend service (Vite/React)
  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    container_name: orthoviewer-frontend
    restart: unless-stopped
    ports:
      - "8001:80"
    depends_on:
      - backend
    networks:
      - orthoviewer-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Backend service (FastAPI)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: orthoviewer-backend
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app
      - ORTHOFINDER_DATA_DIR=/data/orthofinder
      - CORS_ORIGINS=http://localhost,http://localhost:8080,http://localhost:8001,http://frontend:80,http://orthoviewer-frontend
    networks:
      - orthoviewer-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # Nginx as reverse proxy - ROCKY VERSION (port 8080)
  nginx:
    image: nginx:alpine
    container_name: orthoviewer-nginx
    restart: unless-stopped
    ports:
      - "8080:80"  # Changed from 80:80 to 8080:80 for rocky
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - orthoviewer-net
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    
networks:
  orthoviewer-net:
    driver: bridge 