version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
      - DEVELOPMENT=true
    ports:
      - "8000:8000"
    command: ["python", "-m", "uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend-vite
      dockerfile: Dockerfile
    volumes:
      - ./frontend-vite:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]