name: orthoviewer2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python
  - python=3.9
  
  # Web Framework & API
  - fastapi>=0.68.0
  - uvicorn>=0.15.0
  - pydantic>=1.8.0
  - python-multipart>=0.0.5
  
  # Flask (legacy support)
  - flask=2.2.3
  - flask-cors=3.0.10
  
  # Data Processing & Scientific Libraries
  - pandas=2.0.0
  - numpy=1.24.2
  - ete3=3.1.3
  - requests=2.28.2
  - rdflib=6.3.2
  - python-dotenv=1.0.0
  - pyyaml=6.0
  
  # Monitoring & Performance
  - prometheus_client>=0.16.0
  - psutil>=5.9.0
  
  # Development & Testing
  - pytest
  - pytest-cov
  - pytest-asyncio
  - mypy
  - flake8
  - black
  - pre-commit
  
  # Package Management
  - pip
  
  # Packages only available via pip
  - pip:
    - prometheus-fastapi-instrumentator
