name: orthoviewer2
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python
  - python=3.9
  
  # Web Framework & API
  - fastapi>=0.68.0
  - uvicorn>=0.15.0
  - pydantic>=1.8.0
  - python-multipart>=0.0.5
  
  # Data Processing & Scientific Libraries
  - pandas
  - numpy
  - ete3
  
  # Monitoring & Performance
  - prometheus_client>=0.16.0
  - psutil>=5.9.0
  
  # Development & Testing
  - pytest
  - pytest-cov
  - pytest-asyncio
  - mypy
  - flake8
  - black
  - pre-commit
  
  # Package Management
  - pip
  
  # Packages only available via pip
  - pip:
    - prometheus-fastapi-instrumentator
