name: orthoviewer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - fastapi>=0.68.0
  - uvicorn>=0.15.0
  - pydantic>=1.8.0
  - python-multipart>=0.0.5
  - prometheus-client>=0.16.0
  - psutil>=5.9.0
  - pandas
  - ete3
  - pytest
  - pytest-cov
  - mypy
  - flake8
  - pip
  - pip:
    - pytest-asyncio
