name: phylo-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.24.0
  - pandas>=2.0.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - ete3>=3.1.2
  - dendropy>=4.5.0
  - biopython>=1.81
  - pyqt=5.15.*
  - fastapi>=0.104.0
  - uvicorn[standard]>=0.24.0
  - pydantic>=2.4.0
  - python-multipart>=0.0.6
  - plotly>=5.17.0
  - pytest>=7.4.0
  - black>=23.9.0
  - flake8>=6.1.0
  - mypy>=1.6.0
  - jupyterlab>=4.0.0
  - nodejs>=18.0.0
  - npm>=9.0.0
  - requests>=2.31.0
  - aiofiles>=23.2.0
  - python-dotenv>=1.0.0
  - pip>=23.0.0
  - pip:
    - slowapi>=0.1.9
    - python-jose[cryptography]>=3.3.0
    - passlib[bcrypt]>=1.7.4
