name: orthoviewer
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Core Python
  - python=3.10
  
  # Web Framework & API
  - fastapi
  - uvicorn
  - pandas
  - numpy
  - scikit-learn
  - pytest
  - requests
  - aiohttp
  - httpx
  - python-dotenv
  
  # Data Processing & Scientific Libraries
  - ete3
  
  # Monitoring & Performance
  - prometheus_client>=0.16.0
  - psutil>=5.9.0
  
  # Development & Testing
  - mypy
  - flake8
  - black
  - pre-commit
  
  # Package Management
  - pip
  
  # Packages only available via pip
  - pip:
    - "fastapi>=0.68.0,<0.69.0"
    - "pydantic>=1.8.0,<2.0.0"
    - "uvicorn[standard]>=0.15.0,<0.16.0"
    - "python-multipart>=0.0.5,<0.0.6"
    - "python-jose[cryptography]>=3.3.0,<3.4.0"
    - "passlib[bcrypt]>=1.7.4,<1.8.0"
    - "sqlalchemy>=1.4.23,<1.5.0"
    - "alembic>=1.7.1,<1.8.0"
    - "pytest>=6.2.5,<6.3.0"
    - "pytest-cov>=2.12.1,<2.13.0"
    - "requests>=2.26.0,<2.27.0"
    - "python-dotenv>=0.19.0,<0.20.0"
